Class {
	#name : #GtStonObjectModelReaderGenericStub,
	#superclass : #Object,
	#instVars : [
		'name'
	],
	#category : 'GToolkit4Epicea-Examples'
}

{ #category : #'llm-generated' }
GtStonObjectModelReaderGenericStub >> name [
	^ name
]

{ #category : #'llm-generated' }
GtStonObjectModelReaderGenericStub >> name: aString [
	name := aString
]

{ #category : #'llm-generated' }
GtStonObjectModelReaderGenericStub >> stonProcessSubObjects: aBlock [
	^ self
]
